version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: example_api_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - example_api_network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: example_api_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      # - redis
    networks:
      - example_api_network
    volumes:
      - .:/usr/src/app
    command: ["uvicorn", "src.__main__:app", "--host", "0.0.0.0", "--reload"]

networks:
  example_api_network:
    name: example_api_network

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/src/databases/.cache